### 학습목표
 - numpy 모듈이 무엇인지 이해한다.
 - ndarray 이해하고 사용 할 수 있다. 
 - 다양한 방법으로 ndarray 생성하기

#### **numpy 사용하는 이유**

 1. 파이썬 리스트 보다 훨씬 빠르다. 
 1. 파이썬 리스트보다 적은 메모리를 사용한다. 
 1. 선형대수, 통계관련 여러 내장 함수들을 빌트인하고 있다. 
    

#### **ndarray**
  - numpy에서 사용되는 다차원 리스트를 표현할 때 사용되는 데이터타입이다. 
  - ndarray는 연속된 메모리를 사용한다. (리스트보다 훨씬 빠르다.) 

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

#### **다양한 방법으로 ndarray 생성하기** 

In [3]:
natest = np.array([1,2,3,4])
natest2 = np.array([[1,2,3],[4,5,6]]) #2차원 배열
print(natest)
print(natest2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [4]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
print(type(natest2))

<class 'numpy.ndarray'>


#### np.array 함수로 생성하기

In [7]:
#위에서 해봄~

#### np.arange 함수로 생성하기

In [8]:
np.arange(10)  #리스트의 range와 동일

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10)  #10 전까지만.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [12]:
np.ones((4,5)) #4행 5열짜리 행렬 만들기. 4X5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((2,3,4)) #3차원 행렬. 3X4짜리 행렬이 2개.

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
np.ones((2,3,4,5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [19]:
np.zeros((3,4)) #값이 0인 행렬

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### np.empty, np.full로 생성하기

In [16]:
# 0으로 채워지는게 아니라. 
# 초기화가 안되어있는 값이라. 빈 배열일 뿐. 0이 아닐수도 있음
np.empty((3,4))  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.empty((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.empty((2,4,5))

array([[[1.81363716e-152, 7.29530122e+175, 6.50944291e+252,
         3.38877494e+175, 3.99255468e+252],
        [3.25139006e+161, 7.22760913e+159, 4.78111609e+180,
         3.17095864e+180, 1.10255749e+214],
        [9.33829898e+252, 7.20366967e+159, 7.21562902e+159,
         3.17095864e+180, 4.70108393e+180],
        [4.71980621e+164, 3.67591189e+228, 2.42766848e-154,
         5.29274605e+199, 9.13611947e+242]],

       [[1.21696631e-152, 1.27734658e-152, 3.69028917e+180,
         8.89749171e+228, 5.53199725e+199],
        [3.17095813e+180, 9.31672791e+242, 1.19439967e+190,
         2.64522469e+185, 5.51999798e+228],
        [1.71457458e+214, 9.76508577e+199, 4.74345622e+164,
         4.76687371e+180, 2.46416444e-154],
        [7.87705057e+276, 1.06112533e-153, 1.69375606e+190,
         9.07652381e+223, 1.66037178e+243]]])

In [18]:
np.full((3,4), 7)  #값을 지정해서 행렬을 만들 수 있음

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [22]:
np.full((2,3,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [23]:
np.eye(3)  #단위 행렬. 대각선 정사각 행렬!?

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기

In [25]:
np.linspace(1, 10, 3) #x축 y축 눈금처럼. 세번째 인자가 눈금!

array([ 1. ,  5.5, 10. ])

In [26]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [27]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [40]:
x = np.arange(1, 16)
print(x)
print(x.shape) #1차원의 경우에는 15, 
x1 = x.reshape(1,15)
x2 = x.reshape(3,5) # x 자체가 변하는게 아니라서 할당이 필요
x3 = x.reshape(3,5,1)
print(x1)
print(x2)
print(x3)
#무조건 reshape가 되는건 아니고, 행렬의 곱이 떨어져야함. 15, = 3 *5

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [31]:
y = np.full((2,3,4),5)
print(y)
y.shape  #몇행 몇열

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


(2, 3, 4)

#### random 서브모듈 


#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성한다. 
 - 0은 포함. 1은 불포함.

In [41]:
np.random.rand(2,3)

array([[0.9721144 , 0.93016366, 0.02529642],
       [0.49340163, 0.17658157, 0.14359929]])

In [42]:
np.random.rand(3,4)

array([[0.95536544, 0.73775701, 0.90578852, 0.53562401],
       [0.2833954 , 0.69990154, 0.10419013, 0.26095753],
       [0.43209965, 0.18437736, 0.2641548 , 0.74184149]])

#### randn함수
 - n: normal distribution(정규분포) 의 줄임말이다. 
 - 정규분포로 샘플링된 랜덤 ndarray 생성한다.

In [44]:
np.random.randn(5)   #중간값을 기준으로 5개

array([-0.24171982, -2.3498278 , -0.82978841, -0.88238168, -0.42385317])

In [45]:
np.random.randn(2,3)

array([[ 0.74528865,  1.71932792, -2.23223889],
       [ 1.53726178, -0.34811495,  0.77801076]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링한다.

In [46]:
np.random.randint(1, 101, size = (3,4)) #1부터 100까지 3행 4열짜리 랜덤행렬

array([[88, 79, 76, 30],
       [39, 72, 43,  4],
       [54, 78, 73, 86]])

In [47]:
# 재실행시 값이 당연히 달라짐,,,
np.random.randint(1, 101, size = (3,4)) 

array([[85,  8, 83, 55],
       [65, 32,  6, 71],
       [82, 74, 51, 87]])

In [48]:
 # => seed를 써야할때다!

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용한다. 

In [57]:
np.random.seed(22)  #숫자는 무얼 주든 상관없다.

In [82]:
np.random.randn(2,3)

array([[ 0.50529937, -0.26135642, -0.24274908],
       [-1.45324141,  0.55458031,  0.12388091]])

In [83]:
np.random.randn(3,4)

array([[ 0.27445992, -1.52652453,  1.65069969,  0.15433554],
       [-0.38713994,  2.02907222, -0.04538603, -1.4506787 ],
       [-0.40522786, -2.2883151 ,  1.04939655, -0.41647432]])

In [84]:
np.random.seed(22) #이걸 수행하고 위 코드를 재실행하면?. 
np.random.randn(2,3) ##다른 코드를 중간에 수행하더라도 똑같이 나옴

array([[-0.09194992, -1.46335065,  1.08179168],
       [-0.23932517, -0.49112914, -1.00227201]])

In [85]:
np.random.seed(10)
np.random.randn(2,3)

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링한다.
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주한다.

In [87]:
np.random.choice(100, size = (3,4))  #100R까지 수 중에서 임의로

array([[ 0, 40, 36, 16],
       [11, 54, 88, 62],
       [33, 72, 78, 49]])

In [90]:
x = np.array([11,22,454,74,8,33])
np.random.choice(x, size = (2,2)) #이중에서 임의로 꺼내서 2,2 로 만들어줘

array([[74, 22],
       [33,  8]])

In [93]:
x = np.array([11,22,454,74,8,33, 11, 6, 8, 8])  #중복되는 값이 있는 배열
np.random.choice(x, size = (2, 2), replace = False) #중복 허용하지 않음. default는 True임

array([[ 33,  22],
       [  8, 454]])

#### 확률분포에 따른 ndarray 생성
 - uniform 
 - normal ...  

In [95]:
np.random.uniform(1.0, 3.0, size = (3,4))  #1부터 3까지 사이의 균일한 값으로 3,4행렬

array([[1.1809187 , 1.60140011, 1.22796872, 2.65736265],
       [1.09379264, 2.2525743 , 2.09517231, 2.63857399],
       [1.39789508, 2.7137006 , 1.70330528, 2.50929538]])

In [97]:
np.random.uniform(1, 10 , size = (3,4))  #1부터 3까지 사이의 균일한 값으로 3,4행렬

array([[3.66365536, 8.95542832, 3.92960474, 2.48514308],
       [4.5327632 , 1.84114337, 8.38995092, 2.36036818],
       [4.45703004, 9.49834641, 9.88862927, 5.10674092]])

In [99]:
#정규분포를 활용한 임의의 분포
np.random.normal(size = (2,2))

array([[0.70816002, 0.84222474],
       [0.2035808 , 2.39470366]])

In [102]:
np.random.normal(size = (5,2))

array([[-0.5017289 ,  1.12878515],
       [-0.69781003, -0.08112218],
       [-0.52929608,  1.04618286],
       [-1.41855603, -0.36249918],
       [-0.12190569,  0.31935642]])