### 학습목표
 1. numpy에서 ndarray의 인덱싱과 슬라이싱을 사용할 수 있다. 
 1. ndarray shape 변경할 수 있다.


In [1]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[0] #첫요소

0

In [4]:
x[-1] #마지막요소

9

In [5]:
x[2] = 100
x

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

* 2차원 행렬 인덱싱

In [7]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
x[0]

array([0, 1, 2, 3, 4])

In [9]:
x[0,0]

0

In [12]:
x[1,3]
x[1,-1]

9

* 3차원 텐서 인덱싱

In [13]:
x = np.arange(36).reshape(3,4,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [14]:
x[0] #첫번째 행렬

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
#7
x[0][2][1]
x[0,2,1]

7

In [21]:
#28
x[-1][-3][-2]
x[-1,-3,-2]

28

In [22]:
#21
x[1][3][-3]
x[1,3,-3]

21

In [24]:
x[1,1,2] = 77
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 77],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [25]:
x[0,0] = [99,98,97]
x

array([[[99, 98, 97],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 77],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [30]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[3:8]  #3번째 자리부터 7번째 자리까지. 8 불포함

array([4, 5, 6, 7, 8])

In [32]:
x[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[3:]

array([4, 5, 6, 7, 8, 9])

* 2차원 행렬 슬라이싱

In [34]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
x[:,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
x[:, 1:-1]  #마지막꺼는 포함이 안되니까

array([[1, 2, 3],
       [6, 7, 8]])

In [40]:
x[:, 3]  #앞에는 슬라이싱, 뒤에는 인덱싱. 인덱싱은 차원을 줄여줌.

array([3, 8])

In [41]:
x[0, :2]

array([0, 1])

In [43]:
x[:1, :2] # 괄호 갯수에 집중,

array([[0, 1]])

* 3차원 텐서 슬라이싱

In [44]:
x = np.arange(54).reshape(2,9,3)

In [45]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [46]:
x[0, :2] #차원이 축소됨

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
x[:1, :2] #차원이 축소 안됨

array([[[0, 1, 2],
        [3, 4, 5]]])

In [55]:
x[0,:2,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

### ndarray 데이터 형태 바꿔보기

#### ravel, np.ravel
  - 다차원배열을 1차원으로 변경한다. 
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F - column 우선 변경

In [67]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
x.ravel() #np.ravel(x)랑 동일

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
# 우선순위를 바꾸면 달라질 수 있다?
x.ravel(order = 'f')  #기본은 c로 되어있음. 열 기준으로 정렬

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [63]:
x.ravel(order = 'c')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### flatten
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [70]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
temp = x.ravel()
print(temp)

temp[0] = 100
print(temp)
print(x)  

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [73]:
temp = x.flatten()
print(temp)

temp[0] = 0
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


#### reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

In [74]:
x = np.arange(36)
print(x)
print(x.shape)
print(x.ndim) #차원을 알려줌

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [77]:
y = x.reshape(6,6)
print(y)
print(y.shape)
print(y.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
(6, 6)
2


In [78]:
x.reshape(6,-1)  #-1을 이용하면. 앞숫자만 정해주면 뒷숫자는 내가 안써도 알아서 해줌

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [80]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [81]:
x.reshape(3,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [82]:
y = x.reshape(3,3,-1)
print(y)
print(y.shape)
print(y.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
