## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해본다.
 1. broadcasting을 이해하고 사용할 수 있다.

In [2]:
import numpy as np
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.16798844 0.53538918 0.60698965 0.99148049 0.32475789]
 [0.8979869  0.50875145 0.38001186 0.05062778 0.74556396]
 [0.61961624 0.74450213 0.31319046 0.11611342 0.92847888]]


#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

#### 연산 함수
 - add, subtract, multiply, divide

In [ ]:
np.add(x,y) #같은 shape를 가진 행렬끼리 연산 가능

In [4]:
np.divide(x,y)

array([[  0.        ,   1.86780016,   3.29494912,   3.02577816,
         12.31686764],
       [  5.56800995,  11.79357818,  18.42047758, 158.01600492,
         12.0713989 ],
       [ 16.13902175,  14.77497444,  38.31534367, 111.95949446,
         15.0784259 ]])

In [6]:
np.subtract(x, y)

array([[-0.16798844,  0.46461082,  1.39301035,  2.00851951,  3.67524211],
       [ 4.1020131 ,  5.49124855,  6.61998814,  7.94937222,  8.25443604],
       [ 9.38038376, 10.25549787, 11.68680954, 12.88388658, 13.07152112]])

In [7]:
np.multiply(x, y)

array([[ 0.        ,  0.53538918,  1.21397929,  2.97444146,  1.29903158],
       [ 4.48993451,  3.0525087 ,  2.66008304,  0.40502226,  6.71007566],
       [ 6.19616242,  8.18952348,  3.75828549,  1.50947448, 12.99870432]])

In [8]:
x + y

array([[ 0.16798844,  1.53538918,  2.60698965,  3.99148049,  4.32475789],
       [ 5.8979869 ,  6.50875145,  7.38001186,  8.05062778,  9.74556396],
       [10.61961624, 11.74450213, 12.31319046, 13.11611342, 14.92847888]])

In [9]:
x / y

array([[  0.        ,   1.86780016,   3.29494912,   3.02577816,
         12.31686764],
       [  5.56800995,  11.79357818,  18.42047758, 158.01600492,
         12.0713989 ],
       [ 16.13902175,  14.77497444,  38.31534367, 111.95949446,
         15.0784259 ]])

In [10]:
z = np.arange(12).reshape(6,2)

In [11]:
# shape가 다른 행렬끼리 연산은? 불가능
x + z

ValueError: operands could not be broadcast together with shapes (3,5) (6,2) 

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [15]:
print(y)

[[0.16798844 0.53538918 0.60698965 0.99148049 0.32475789]
 [0.8979869  0.50875145 0.38001186 0.05062778 0.74556396]
 [0.61961624 0.74450213 0.31319046 0.11611342 0.92847888]]


In [12]:
np.mean(y)

0.5287632495995185

In [13]:
y.mean()

0.5287632495995185

In [14]:
np.max(y)

0.991480485693092

In [16]:
#최대값의 index를 구해줘
# flatten 한 상태에서의 index임!!!!
np.argmax(y)

3

In [17]:
np.median(y)

0.5353891828339578

In [18]:
np.std(y)

0.2895788223198203

In [19]:
np.var(y)

0.08385589433613407

In [20]:
np.min(y)

0.050627782953083456

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [21]:
np.sum(y)

7.931448743992777

In [22]:
#각각의 자리에서 다음거랑 누적 누적 누적하는 식

np.cumsum(y) 

array([0.16798844, 0.70337762, 1.31036727, 2.30184775, 2.62660565,
       3.52459255, 4.033344  , 4.41335586, 4.46398365, 5.20954761,
       5.82916385, 6.57366598, 6.88685644, 7.00296986, 7.93144874])

In [24]:
print(y)

[[0.16798844 0.53538918 0.60698965 0.99148049 0.32475789]
 [0.8979869  0.50875145 0.38001186 0.05062778 0.74556396]
 [0.61961624 0.74450213 0.31319046 0.11611342 0.92847888]]


In [23]:
sum(y)  #각 열마다 합계함.

array([1.68559158, 1.78864277, 1.30019197, 1.15822169, 1.99880074])

In [25]:
np.sum(y, axis = None)  #None이 default

7.931448743992777

In [26]:
np.sum(y, axis = 0)   #축의 기준 0. 각 열마다 합계인 것으로 산출됨 == sum(y)

array([1.68559158, 1.78864277, 1.30019197, 1.15822169, 1.99880074])

In [27]:
np.sum(y, axis = 1) #각 행의 합계로 산출됨.

array([2.62660565, 2.58294196, 2.72190114])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [28]:
#DBMS 집계함수 할 ㄸㅐ 쓰던 ANY ALL!!!!
x = np.random.randn(10)
x

array([-0.1146894 ,  0.49743964,  0.32445078,  1.28407398,  0.65919599,
        1.10249449,  2.027624  ,  1.0040247 ,  1.13175561, -1.9032137 ])

In [29]:
x > 0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [30]:
np.any(x > 0) #요소 하나라도 0보다 크면 True

True

In [31]:
np.all(x>0) # 모두 0보다 커야 True

False

In [32]:
np.all(x != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [33]:
x

array([-0.1146894 ,  0.49743964,  0.32445078,  1.28407398,  0.65919599,
        1.10249449,  2.027624  ,  1.0040247 ,  1.13175561, -1.9032137 ])

In [34]:
np.where(x > 0, x , 0)  #조건이 참이라면 x를 주고 거짓이면 0

array([0.        , 0.49743964, 0.32445078, 1.28407398, 0.65919599,
       1.10249449, 2.027624  , 1.0040247 , 1.13175561, 0.        ])

axis =  축  = 차원 

2차원은 0,1   1차원은 0  3차원 텐서는 0,1,2 의 값을 갖는다.  



#### axis 이해하기
 - 몇몇 함수에는 axis keyword 파라미터가 존재한다.
 - axis값이 없는 경우에는 전체 데이터에 대해 적용한다.
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용한다.
 


 * axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
 - 예) np.sum, np.mean, np.any 등등
 

In [35]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.sum(x)

105

In [38]:
np.sum(x, axis = 1)  #1차원짜리엔 축이 하나뿐이라 0이 최대임.

AxisError: axis 1 is out of bounds for array of dimension 1

* 행렬에 적용하기 

In [39]:
y = x.reshape(3,5)
y 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
np.sum(y)

105

In [42]:
np.sum(y, axis = 0)

array([15, 18, 21, 24, 27])

In [41]:
np.sum(y, axis = 1)

array([10, 35, 60])

In [ ]:
#np.sum(y, axis = 2)

In [44]:
z = np.arange(30).reshape(2,3,5)
z

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [45]:
np.sum(z, axis = 0)  #축이 첫번째 차원부터 들어감!

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [47]:
np.sum(z, axis = 1) #각 행렬 내에서 열 축으로 합계

array([[15, 18, 21, 24, 27],
       [60, 63, 66, 69, 72]])

In [49]:
np.sum(z, axis = 2) #각 행렬 내에서 행 축으로 합계

array([[ 10,  35,  60],
       [ 85, 110, 135]])

* axis의 값이 튜플일 경우
   - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [50]:
np.sum(z, axis = (0, 1)) #다시 y축으로 연산

array([75, 81, 87, 93, 99])

#### 브로드캐스팅
  
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    

#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능
 
 ![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

##### 마지막 차수가 맞아야함.
4X3 + 1X3 = 4X3

* Shape이 같은 경우의 연산

In [52]:
x = np.arange(15).reshape(3,5)

* 상수와의 연산 

In [54]:
x*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

* shape이 다른 경우 연산

In [55]:
x = np.arange(12).reshape(4,3)
y = np.arange(100, 103)

In [57]:
print(x)
print(x.shape)
print(y)
print(y.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[100 101 102]
(3,)


In [58]:
x + y

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [59]:
z = np.arange(100, 104)
print(z)
print(z.shape)

[100 101 102 103]
(4,)


In [60]:
x + z #안됨. 
#왜냐? shape에서 열 축의 크기가 같아야함. shape의 끝나는 숫자가 같아야함.

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 