### NumPy 실습문제

예제: https://leechamin.tistory.com/29?category=827917

1. 0으로 채워진 크기가 20인 배열을 생성하세요.

In [2]:
import numpy as np
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요.

In [3]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.

In [5]:
x = np.zeros(10)
x[2] = 1
x

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

4. 1에서 10까지의 값을 갖는 배열을 생성하세요.

In [8]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5. 위의 배열의 순서를 거꾸로 바꿔주세요.

In [9]:
x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

6. 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. 랜덤한 값을 가지는 3X3X3 배열을 생성하세요.

In [17]:
y = np.random.rand(3,3,3)

8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요.

In [18]:
np.mean(y)
np.max(y)

0.9986353177439647

9. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오.
참고: numpy에서 평균을 구하는 함수 - mean()

In [25]:
y = np.random.rand(20)
np.mean(y)

0.4379592446925756

10. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요.

In [24]:
arr = np.zeros((4,4))
arr[0:1] = 1
arr[-1:] = 1
arr[:,0:1] = 1
arr[:,-1:] = 1
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## 여기서부터 실습
- numpy100제(위에 링크)
- p.214부터 Numpy 연습하기

In [26]:
import numpy as np

In [27]:
print(np.__version__)

1.16.5


In [28]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
print('%d bytes'%(z.size * z.itemsize))

80 bytes


In [30]:
%run python -c'import numpy; numpy.info(numpy.add)''

ERROR:root:File `'python.py'` not found.


In [31]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [34]:
z = np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
z = [1,2,0,0,4,0]
np.nonzero(z)  #0이 아닌 요소 인덱스 찾기

(array([0, 1, 4], dtype=int64),)

In [36]:
z = np.eye(3,3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
z = np.random.rand(3,3,3)
z

array([[[0.65943872, 0.72710288, 0.49643488],
        [0.61268731, 0.17694463, 0.11246689],
        [0.23327317, 0.66114496, 0.15878893]],

       [[0.12509772, 0.05276485, 0.75512751],
        [0.42213888, 0.03211607, 0.16699659],
        [0.71591246, 0.67583665, 0.02414746]],

       [[0.58968827, 0.2834599 , 0.54952302],
        [0.71622735, 0.05274533, 0.16289424],
        [0.02318943, 0.33648207, 0.85465434]]])

In [42]:
z = np.random.rand(10,10)
np.min(z)
np.max(z)

0.9954893856026998

In [44]:
z = np.random.rand(30)
z
z.mean()

0.46340281918705656

In [52]:
z = np.ones((10,10))
print(z)
z[1:-1, 1:-1] = 0 #마지막거는 포함 안됨! 
z

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
z = np.zeros((5,5))
z[1:-1, 1:-1] = 1
z

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
print( 0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print( -.3 == 3 * 0.1)

nan
False
False
nan
True
False
