## 학습목표
 1. pandas 라이브러리를 이해한다.
 1. pandas Series 데이터를 이해한다.
 1. Series 함수 활용하여 데이터 분석한다.
 1. Series 데이터를 다양한 방법으로 연산 및 조작할 수 있다. 

### 1. pandas 
- 테이블형(행렬) 데이터를 다룰 수 있는 다양한 기능을 가진 라이브러리이다.
- raw data(원시)를 데이터 분석 전과정을 위해 사용할 수 있도록 변환하는 데이터 전처리에도 많이 사용된다.


설명:   - raw data: 아직 데이터 분석을 위해 정제되지 않은 기본 데이터를 의미함
    - 보통 데이터 분석 목적에 맞지 않은 불필요한 데이터가 있거나, 데이터가 없는 열들이 포함됨

#### 판다스(pandas) 맛보기.

In [1]:
import pandas as pd

In [2]:
student_df = pd.read_csv('student.csv')

In [3]:
student_df

이름  나이            주소
0  오혜인  20   경기도 용인시 수지구
1  강경미  20  경기도 고양시 일산동구
2  홍길동  10   서울시 종로구 혜화동

In [4]:
type(student_df) #전체 데이터는 데이터프레임 형태.

pandas.core.frame.DataFrame

In [5]:
student_df.이름

0    오혜인
1    강경미
2    홍길동
Name: 이름, dtype: object

In [6]:
type(student_df.이름) #한개의 속성은 시리즈 형태.

pandas.core.series.Series

### 2. Series - pandas 가 제공하는 객체.
  -  데이터를 다루기 위해 데이터 프레임(Dataframe)과 시리즈(Series) 제공한다.
  - 시리즈(Series)는 numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타낸다.
 -  데이터프레임(Dataframe)이 테이블형(2차원) 데이터이다.

In [7]:
s1 = pd.Series([1,2,3])
s1  #인덱스가 앞에 자동으로 붙음.

0    1
1    2
2    3
dtype: int64

In [8]:
s2 = pd.Series(['a', 'b', 'c'])
s2  #문자형 데이터는 모두 오브제젝트로 나옴

0    a
1    b
2    c
dtype: object

In [9]:
import numpy as np

In [10]:
s3 = pd.Series(np.arange(100, 200, 10))
s3

0    100
1    110
2    120
3    130
4    140
5    150
6    160
7    170
8    180
9    190
dtype: int32

In [11]:
s3.head()

0    100
1    110
2    120
3    130
4    140
dtype: int32

In [12]:
s3.tail()

5    150
6    160
7    170
8    180
9    190
dtype: int32

In [15]:
s4 = pd.Series([1,2,3], [100, 200, 300])  #인덱스를 직접 부여할 수 있음
s4

100    1
200    2
300    3
dtype: int64

In [16]:
s5 = pd.Series([1,2,3],['a', 'b', 'c']) #인덱스가 반드시 숫자일 필요는 없다
s5

a    1
b    2
c    3
dtype: int64

In [17]:
s6 = pd.Series(np.arange(5), np.arange(100,105), dtype = object)
s6

100    0
101    1
102    2
103    3
104    4
dtype: object

#### 인덱스 활용하기

In [18]:
s6.index  #인덱스 속성

Int64Index([100, 101, 102, 103, 104], dtype='int64')

In [19]:
s6.values

array([0, 1, 2, 3, 4], dtype=object)

1. 인덱스를 통한 데이터 접근

In [20]:
s6[101]

1

In [22]:
#s6[105]  #없는 인덱스 - 에러
s6[104]

4

2. 인덱스를 통한 데이터 업데이트

In [24]:
s_name = student_df.이름

In [25]:
s_name[0]

'오혜인'

In [26]:
s_name[3] = '고소영'

C:\Users\ohi02\Anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [27]:
s_name

0    오혜인
1    강경미
2    홍길동
3    고소영
Name: 이름, dtype: object

In [28]:
s_name[1] = '둘리'

In [29]:
s_name

0    오혜인
1     둘리
2    홍길동
3    고소영
Name: 이름, dtype: object

In [30]:
s6[200]= 100

In [31]:
s6

100      0
101      1
102      2
103      3
104      4
200    100
dtype: object

3. 인덱스 재사용하기

In [32]:
s7 = pd.Series(np.arange(6), s6.index)  #인덱스값을 s6의 인덱스값으로 주고싶다.

In [33]:
s7

100    0
101    1
102    2
103    3
104    4
200    5
dtype: int32

#### **Series size, shape, unique, count, value_counts 함수**
 - size : 개수를 반환한다.  len() 과 유사하다. 
 - shape : 튜플형태로 shape반환한다.
 - unique: 유일한 값만 ndarray로 반환한다.
 - count : NaN을 제외한 개수를 반환한다.
 - mean: NaN을 제외한 평균값을 구한다.
 - value_counts: NaN을 제외하고 각 값들의 빈도를 반환한다. 

In [34]:
len(s6)

6

In [35]:
len(s_name)

4

In [36]:
s_name.size

4

In [37]:
s = pd.Series([1,1,2,4,2,2,6,4,8,4,6,48,88,9,55, np.NaN])  # 논값을 가진 시리즈 생성
s

0      1.0
1      1.0
2      2.0
3      4.0
4      2.0
5      2.0
6      6.0
7      4.0
8      8.0
9      4.0
10     6.0
11    48.0
12    88.0
13     9.0
14    55.0
15     NaN
dtype: float64

In [38]:
len(s)

16

In [39]:
s.size

16

In [40]:
s.shape

(16,)

In [41]:
s.unique()  #중복값 빼고 새 리스트를 만들어줌

array([ 1.,  2.,  4.,  6.,  8., 48., 88.,  9., 55., nan])

In [42]:
s.count()  # nan 값을 제외하고 값을 세줌

15

In [43]:
s.mean()  #series는 numpy와 달리 nan이 있어도 그냥 계산

16.0

In [44]:
n1 = np.array([1,1,2,4,2,2,6,4,8,4,6,48,88,9,55, np.NaN])
n1.mean()   #난값이 들어있으면 제대로 계산이 안되고 nan이 됨.

nan

In [46]:
s.value_counts()

4.0     3
2.0     3
6.0     2
1.0     2
55.0    1
9.0     1
88.0    1
48.0    1
8.0     1
dtype: int64

In [61]:
s.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
dtype: bool

#### **head, tail 함수**
 - head : 상위 n개 출력 기본 5개
 - tail : 하위 n개 출력 기본 5개

In [49]:
s

0      1.0
1      1.0
2      2.0
3      4.0
4      2.0
5      2.0
6      6.0
7      4.0
8      8.0
9      4.0
10     6.0
11    48.0
12    88.0
13     9.0
14    55.0
15     NaN
dtype: float64

In [47]:
s.head(3)  #default는 5개

0    1.0
1    1.0
2    2.0
dtype: float64

In [48]:
s.tail(6)

10     6.0
11    48.0
12    88.0
13     9.0
14    55.0
15     NaN
dtype: float64

#### Series 데이터 연산하기

In [51]:
s1 = pd.Series([1,2,3,4], ['a', 'b', 'c', 'd'])
s2 = pd.Series([6,3,7,8], ['d', 'a', 'b', 'c'])
print(s1)
print(s2)

a    1
b    2
c    3
d    4
dtype: int64
d    6
a    3
b    7
c    8
dtype: int64


In [52]:
s1 + s2  #순서가 아니라 인덱스 기준으로 연산을 해줌

a     4
b     9
c    11
d    10
dtype: int64

* **산술연산**
 - Series의 경우에도 스칼라와의 연산은 각 원소별로 스칼라와의 연산이 적용된다.
 - Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용된다.
   - 이때, 인덱스의 짝이 맞지 않으면, 결과는 NaN 

In [53]:
s1 * 2

a    2
b    4
c    6
d    8
dtype: int64

In [54]:
s1 * s2  #인덱스끼리 연산이 된다.

a     3
b    14
c    24
d    24
dtype: int64

In [55]:
#서로에게 없는 인덱스를 추가해보자.
s1['e'] = 7   
s2['f'] = 9
print(s1)
print(s2)

a    1
b    2
c    3
d    4
e    7
dtype: int64
d    6
a    3
b    7
c    8
f    9
dtype: int64


In [56]:
s1 + s2  # 짝이 없는 애들은 NaN 반환

a     4.0
b     9.0
c    11.0
d    10.0
e     NaN
f     NaN
dtype: float64

In [57]:
s1 * s2 #짝이 없는 애들은 NaN 반환

a     3.0
b    14.0
c    24.0
d    24.0
e     NaN
f     NaN
dtype: float64

#### Series boolean selection 활용하기

  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함된다.
  - 다중조건의 경우, &(and), |(or)를 사용하여 연결 가능하다.

In [18]:
import numpy as np
import pandas as pd

In [66]:
s1

a    1
b    2
c    3
d    4
e    7
dtype: int64

In [78]:
s1[3]

4

In [63]:
a = s1 > 6
a
type(a)

pandas.core.series.Series

In [64]:
s1[a]  #True인 결과만 나옴

e    7
dtype: int64

In [65]:
s1[s1>6]

e    7
dtype: int64

In [67]:
s1[s1%2 ==0]

b    2
d    4
dtype: int64

In [74]:
s1[s1%3 == 0]

c    3
dtype: int64

In [69]:
s = pd.Series(np.arange(10), np.arange(10) + 1)
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [70]:
s.index > 5  #인덱스만 기준으로 봄.

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
s[(s.index > 5) & (s.index < 8)]

6    5
7    6
dtype: int32

In [75]:
s >= 7  #값을 기준으로 봄

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
dtype: bool

In [76]:
(s>=7).sum()   # True의 갯수

3

In [77]:
# 값의 합을 알고 싶으면
s[s>=7].sum()

24

#### Series 값 변경



In [79]:
import pandas as pd
import numpy as np
s = pd.Series(np.arange(100, 105), ['a', 'b', 'c', 'd', 'e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [80]:
s['a'] = 200
s

a    200
b    101
c    102
d    103
e    104
dtype: int32

In [81]:
s['k'] = 300
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [82]:
s.drop('k')  #k가 삭제된 복사본. 재할당을 해야만 원본을 바꿀 수 있음.

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [83]:
s   #drop은 원본은 그대로 남김.

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [84]:
s.drop('k', inplace = True)  #원본을 바꾸고 싶다면?
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [85]:
del s['a']  #한번에 원본에서 삭제해줌.
s

b    101
c    102
d    103
e    104
dtype: int64

In [86]:
s['a', 'b'] = [200, 200] #안됨. 에러남. 여러개 안됨....!!

KeyError: "['a'] not in index"

In [87]:
# 여러개를 하고 싶다면 하나의 리스트로 넘겨야 함~~
s[['b', 'd']] = [200, 200]

In [88]:
s

b    200
c    102
d    200
e    104
dtype: int64

In [89]:
s[('b', 'd')] = [300, 300] #튜플도 되넴.
s

b    300
c    102
d    300
e    104
dtype: int64

In [90]:
s2 = pd.Series(np.arange(100, 105), ['a', 'b', 'c', 'd', 'e'])
s2[1:3]  #인덱스값이 아니더라도 숫자로 인식 가능.

b    101
c    102
dtype: int32

In [91]:
s2['c':'d'] #숫자랑 문자열로 인덱스로 준게 다른 점은 문자열의 경우 자기까지 포함

c    102
d    103
dtype: int32

##### 날짜 자동생성 
* pd.date_range(start=None, end=None,periods=None, freq='D')
* periods 날짜데이터 생성기간 freq = 날짜데이터생성주기 ferq 는 'D' 가 기본값. 
* start - 시작날짜.  반드시 필요.  end나 periods는 둘 중 하나만 있어도 됨.


- 파이썬 철저입문 p241 ~~  246까지

In [93]:
pd.date_range(start = '2020-12-14', end = '2021-01-08')

DatetimeIndex(['2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17',
               '2020-12-18', '2020-12-19', '2020-12-20', '2020-12-21',
               '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25',
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31', '2021-01-01', '2021-01-02',
               '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06',
               '2021-01-07', '2021-01-08'],
              dtype='datetime64[ns]', freq='D')

In [94]:
pd.date_range(start = '2020-12-14',periods = 7)

DatetimeIndex(['2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17',
               '2020-12-18', '2020-12-19', '2020-12-20'],
              dtype='datetime64[ns]', freq='D')

In [95]:
pd.date_range(start = '2020-12-14',periods = 7, freq = '2D')  #이틀간격

DatetimeIndex(['2020-12-14', '2020-12-16', '2020-12-18', '2020-12-20',
               '2020-12-22', '2020-12-24', '2020-12-26'],
              dtype='datetime64[ns]', freq='2D')

In [96]:
pd.date_range(start = '2020-12-31', end = '2021-01-07')

DatetimeIndex(['2020-12-31', '2021-01-01', '2021-01-02', '2021-01-03',
               '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07'],
              dtype='datetime64[ns]', freq='D')

In [97]:
pd.date_range(start = '2020-12-31', end = '2021-01-07', freq = '3D')

DatetimeIndex(['2020-12-31', '2021-01-03', '2021-01-06'], dtype='datetime64[ns]', freq='3D')