In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.ones((2,3))    
y = np.array([[10],[20]])    
print(x * y )

[[10. 10. 10.]
 [20. 20. 20.]]


In [3]:
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
json_dict = {
     "거주지": "서울",
     "나이": 25,
     "신체정보": {
        "몸무게": 71.2,
        "키": 175.4
     }  }
json_dict

{'거주지': '서울', '나이': 25, '신체정보': {'몸무게': 71.2, '키': 175.4}}

In [8]:
json_dict['신체정보']['몸무게']

71.2

In [9]:
np.random.randint(10, size=(3, 4))

array([[7, 9, 7, 7],
       [6, 5, 0, 6],
       [8, 6, 0, 9]])

In [10]:
df = pd.read_csv('employees.csv')
df.head()

Unnamed: 0  EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  \
0           0          100     Steven      King     SKING  515.123.4567   
1           1          101      Neena   Kochhar  NKOCHHAR  515.123.4568   
2           2          102        Lex   De Haan   LDEHAAN  515.123.4569   
3           3          103  Alexander    Hunold   AHUNOLD  590.423.4567   
4           4          104      Bruce     Ernst    BERNST  590.423.4568   

    HIRE_DATE   JOB_ID   SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID  
0  2003-06-17  AD_PRES  24000.0             NaN         NaN           90.0  
1  2005-09-21    AD_VP  17000.0             NaN       100.0           90.0  
2  2001-01-13    AD_VP  17000.0             NaN       100.0           90.0  
3  2006-01-03  IT_PROG   9000.0             NaN       102.0           60.0  
4  2007-05-21  IT_PROG   6000.0             NaN       103.0           60.0

In [11]:
df.iloc[[10, 30, 100]]

Unnamed: 0  EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  \
10           10          110       John      Chen     JCHEN  515.124.4269   
30           30          130      Mozhe  Atkinson  MATKINSO  650.124.6234   
100         100          200   Jennifer    Whalen   JWHALEN  515.123.4444   

      HIRE_DATE      JOB_ID  SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID  
10   2005-09-28  FI_ACCOUNT  8200.0             NaN       108.0          100.0  
30   2005-10-30    ST_CLERK  2800.0             NaN       121.0           50.0  
100  2003-09-17     AD_ASST  4400.0             NaN       101.0           10.0

In [12]:
grade_df[grade_df['영어점수'] >= 80]

NameError: name 'grade_df' is not defined

In [20]:
import requests
from bs4 import BeautifulSoup as bs
url = 'https://www.python.org/static/img/python-logo.png'
html_image = requests.get(url)

In [26]:
html_image.text

'�PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01"\x00\x00\x00R\x08\x06\x00\x00\x00����\x00\x00\x00\tpHYs\x00\x00\x0b\x13\x00\x00\x0b\x13\x01\x00��\x18\x00\x00 \x00IDATx��w|\x14e��?���M�(�@�\x10�4��4��\x05E \x12\x08\x02�(\x1eV\x10<�;��g9ς����x\x16H \x10�!x (��D !�\x00*Dž"\x08\x04R����<�?6�L6[�.\x01�w^�ڙ��g������!�R((((�\'L{\x17@AAAA\x11"\x05\x05�vG\x11"\x05\x05�vG\x11"\x05\x05�vG\x11"\x05\x05�vG\x11"\x05\x05�vG\x11"\x05\x05�vG\x11"���w;w�l�B(\\:(B�\x10v\x08!�����u���:r��\x7f(��3f�����R�tP]��H焈�H&����]�\x1d���v�+%�#�4�Rh)�R*�A�\x05�\u058b g\x18�=~|念\\��_\x1b�W��b�W!4lݺu�m��V ���j�B\x14E�t:��˥p�\x10v!"��!�����\\�o��y�$�"\x1f\x0f\n-�\x14����\x02���\x14�k\x14\x14"��|�R��\'�\x02���\\p�|�zY���.�5?6���\n��j��\t��5���%�=ˣp�\x11V!J�<wب7�\x17��\x11���\x0e��\x04@&:p�C\x14]ǴY����\x14\x14�b\x0c��\x0c��O\x1e<d�K��s�cO\x1c���\x0f�,�Bh\x10EQ��-\x00(�\x1b\x15�\t��(e��\x03~�1�K°�vK\x13,\x16\x0b�v\x1e\x16�\x07/�\x00�\x16\x0f\\�\x04�u\x04�(A��\x00Q\x14చ@\x18��u��M�e��p�_!���L�\x14\x14$�b\x11\x11BȨ���E�T\x17-�\

In [34]:
soup = bs(html_image.text)
soup  = soup.find('image')

In [35]:
soup

In [25]:
a2 = np.array([[10, 20, 30], [47, 57, 67], [70, 80, 95]])
a2[[0, 2], [0, 1]]

array([10, 80])

In [37]:
b2 =  np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b2[:3, 1:] 

array([[20, 30],
       [50, 60],
       [80, 90]])

In [39]:
a1 = np.array( [ 0, 10, 20, 30, 40, 50 ] ) 
a1[[1,3,4]]

array([10, 30, 40])

In [46]:
df_left = pd.DataFrame(['A',1],[ 'B',2], ['C',3])
df_left

ValueError: Shape of passed values is (2, 1), indices imply (2, 2)